Update chocolatey package to tektoncd-cli version 0.7.0
danielhelfand/chocolatey-tektoncd-cli pull request #2
Opened 2020-02-03 21:54 UTC by ducksecops

2020-02-04 13:56 UTC, danielhelfand requested changes
@ducksecops Thanks so much for this! 

Unfortunately, there was an issue releasing `v0.7.0` that is requiring a minor release today. There was a [`gotest.tools` issue](https://github.com/gotestyourself/gotest.tools/pull/184) that required us to use a fork of `gotest.tools` for the release.

If you would be willing, it would be great if we could repurpose this pr for the minor release (`v0.7.1`) today. Let me know, and I can update you when the release is available.

2020-02-04 14:27 UTC, danielhelfand commented
Released for [v0.7.1](https://github.com/tektoncd/cli/releases/tag/v0.7.1).

2020-02-04 15:20 UTC, ducksecops commented
Hi,

Update to version 0.7.1.

Regards

2020-02-04 16:04 UTC, danielhelfand reviewed
Just minor change, and could you also please squash this into one commit?

2020-02-04 16:04 UTC, danielhelfand commented on tektoncd-cli/tools/chocolateyinstall.ps1
> +  checksum64     = 'SHA256: 592C79C96FCE12B8E8DC4F853C1D8D6FAC76E18AC7A3B2118D44A238A5274875
Could you change to:

```suggestion
  checksum64     = '592c79c96fce12b8e8dc4f853c1d8d6fac76e18ac7a3b2118d44a238a5274875'
```

2020-02-05 17:29 UTC, danielhelfand commented
@ducksecops Thanks! Could you please squash these commits into a single one?

2020-02-06 13:42 UTC, danielhelfand commented
Closing this in favor of [33bfcb9](https://github.com/danielhelfand/chocolatey-tektoncd-cli/commit/33bfcb9d9e13b051ef41155985f7140162840b32).

2020-02-06 13:42 UTC, closed without merging